### ISSUE TITLE
Help with ESPhome template for Martin Jerry 3-way switch

### ISSUE THREAD

**Issue by ikrowni** [mjoshd/esphome_martin-jerry-mj-s01-switch#1]
Hello i've been using your templates for most of my light switches as you seem to be using a lot of the martin jerry switches as well. The only problem is it looks like you swapped over to MOES 3 way switches. I'm pretty new to ESPhome and was hoping i could ask for your help in making the template for the martin jerry 3-way switches? Here's the link to the Tasmota template that works for them 

https://templates.blakadder.com/martin-jerry-3-way-ST01.html

I know this probably wont benefit your setup any and i'm sorry for bothering you with it i just wanna make sure I don't burn my house down trying to get it right.

**Comment by mjoshd** [comment]
Hi.

All of the ESPHome device templates that I've put on github are only added after I've had a chance to personally write, test, and verify the code/functionality with the device in-hand. 

I do not have any Martin Jerry ST01 switches and therefore won't be able to create a config for it.

I am sorry but I am not comfortable or willing to provide untested code that may, potentially, cause a crisis-level event at your home in much the same way that you don't want to cause damage/fire by accidentally doing something wrong.

I would suggest locating another user on the HA forums who also owns the same device model and has interest in creating an ESPHome configuration for it.

Alternatively, it appears that Tasmota already offers a template for the device (the link you provided) which will likely 'just work' if the documented steps are followed. Here's a [Martin Jerry ST01 + Tasmota full setup video by DigiBlur](https://www.youtube.com/watch?v=B8YhfZ_LguI).

If you are intent on creating an ESPHome config for this device I would suggest doing the same thing I did: create a fully exposed mockup of a functional 3-way circuit (circuit breaker, smart 3-way switch, regular 3-way switch, traveler wires, light bulb, etc.) on your work-bench/area so you can see very easily how it is behaving and very quickly notice if anything goes wrong (absolutely do not do this kind of testing with wiring that is already installed in your walls).

Wishing you the best of luck, whichever route you choose.

**Comment by ikrowni** [comment]
Thanks for the information I had no idea that was really an issue I could have. I thought it would just not work if I didn't do it right. Thanks again for letting me know.

**Comment by mjoshd** [comment]
3 way switches are quite different than normal switches as one of the traveler wires is always carrying electricity.  While the chances of incorrect configuration causing fire are low they are still there. Perhaps I'm just overly cautious but I would rather not take any chances.
